
#actutatr-config
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    with:
      exposure:
        include: "*"

#zipkin-config
management.tracing.sampling.probability: 1.0
spring.zipkin.baseUrl: http://localhost:9411


